### ISSUE TITLE
fatal: remote origin already exists.

### ISSUE THREAD

**Issue by pengshiyu** [Solybum/hexo-deploy#2]
![image](https://user-images.githubusercontent.com/83739918/117237696-10fb5e00-ae5e-11eb-9537-1ec37584c3bb.png)

**Comment by pengshiyu** [comment]
copy CNAME if exists
Config git ...
Reinitialized existing Git repository in /github/workspace/.git/
fatal: remote origin already exists.

**Comment by Solybum** [comment]
Hello!
Sorry I no longer use Hexo, I would recommend you to use the actions they suggest in their website.
https://hexo.io/docs/github-pages.html

Delete `.github/workflows/deploy.yml`
Create `.github/workflows/pages.yml`
```
name: Pages

on:
  push:
    branches:
      - master # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Hexo Clean
        run: npm run clean
      - name: Hexo Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HEXO_TOKEN }}
          publish_dir: ./public
```
